spring.application.name=auth-service
server.port=8090

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.data.redis.host=redis-server
spring.data.redis.port=6379

# JWT
jwt.secret=THIS_IS_A_VERY_LONG_SECRET_KEY_FOR_MICROSERVICE_JWT_AUTH_123456789
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000

# LOG
logging.level.org.springframework.security=INFO