spring.application.name=booking-service

server.port=8087

spring.datasource.url=jdbc:mysql://mysql-db:3306/booking_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# OPENFEIGN CIRCUIT BREAKER
spring.cloud.openfeign.circuitbreaker.enabled=true

# FEIGN TIMEOUT
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=3000
# RESILIENCE4J CIRCUIT BREAKER
resilience4j.circuitbreaker.instances.eventService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.eventService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.eventService.waitDurationInOpenState=10s
# ACTUATOR
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs