spring.application.name=payment-service

server.port=8088

spring.datasource.url=jdbc:mysql://mysql-db:3306/payment_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

vnpay.tmn-code=5CLRSAIZ
vnpay.hash-secret=7RUT0VKORC4REQ7GX8FGT6HOJPOF06DV
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/payment-service/payments/vnpay-return
vnpay.frontend-return-url=http://localhost:5174/payment-result

# ACTUATOR
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always